project:
  type: website
  render:
    - "*.md"
    - "wyklady/*.md"
    - "laby/*.md"
    - "!*.ipynb"

website:
  title: "Automatyczne pozyskiwanie danych"
  description: "Materiały do kursu"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.md
      - section: "Wykłady"
        contents:
          - wyklady/wyklad_1.md
          - wyklady/wyklad_2.md
          - wyklady/wyklad_3.md
          - wyklady/wyklad_4.md
          - wyklady/wyklad_5.md
          - wyklady/wyklad_6.md
          - wyklady/wyklad_7.md
      - section: "Laboratoria"
        contents:
          - laby/lab_0.md
          - laby/lab_1.md
          - laby/lab_2.md
          - laby/lab_3.md
          - laby/lab_4.md
          - laby/lab_5.md
          - laby/lab_6.md

format:
  html:
    theme: sandstone
    toc: true
    toc-title: "Spis treści"
    number-sections: true
    code-copy: true
    syntax-highlighting: pygments
